[package]
name = "tsukiyo-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.36.0"
log = "0.4"
env_logger = "0.11.7"
fltk = { version = "1.5.6", features = ["fltk-bundled"] }
pdfium-render =  "0.8.29"
image = { version = "0.25.6", default-features = true }